# Generated by Django 3.0.3 on 2020-02-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('logo', models.CharField(max_length=1000)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
